source=~/.config/hypr/hyprland/animation.conf
source=~/.config/hypr/hyprland/general.conf
source=~/.config/hypr/hyprland/keybind.conf
source=~/.config/hypr/hyprland/startup.conf
source=~/.config/hypr/hyprland/rule.conf
