bind = SUPER, T, exec, kitty --session ~/.bashrc
bind = SUPER, F, exec, firefox
bind = SUPER, Q, killactive
bind = SUPER, M, exec, hyprctl dispatch exit

bind = SUPER, R, exec, rofi -show run

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2

bind = CTR+SUPER, Right, workspace, +1
bind = CTR+SUPER, Left, workspace, -1

