bind = SUPER, T, exec, kitty --session ~/.bashrc
bind = SUPER, F, exec, firefox
bind = SUPER, Q, killactive
bind = SUPER, M, exec, hyprctl dispatch exit

bind = SUPER, R, exec, rofi -show run

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Win + num to switch workspace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

#Win + Alt + num to move window silent to another workspace
bind = SUPER+ALT, 1, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 1 0
bind = SUPER+ALT, 2, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 2 0
bind = SUPER+ALT, 3, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 3 0
bind = SUPER+ALT, 4, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 4 0
bind = SUPER+ALT, 5, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 5 0
bind = SUPER+ALT, 6, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 6 0
bind = SUPER+ALT, 7, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 7 0
bind = SUPER+ALT, 8, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 8 0
bind = SUPER+ALT, 9, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 9 0

#Win + Alt + Shift + num to move window to another workspace
bind = SUPER+ALT+SHIFT, 1, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 1 1
bind = SUPER+ALT+SHIFT, 2, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 2 1
bind = SUPER+ALT+SHIFT, 3, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 3 1
bind = SUPER+ALT+SHIFT, 4, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 4 1
bind = SUPER+ALT+SHIFT, 5, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 5 1
bind = SUPER+ALT+SHIFT, 6, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 6 1
bind = SUPER+ALT+SHIFT, 7, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 7 1
bind = SUPER+ALT+SHIFT, 8, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 8 1
bind = SUPER+ALT+SHIFT, 9, exec, sh ~/.config/hypr/script/move_window_to_ws.sh 9 1

binde =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
binde =, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindle=, XF86MonBrightnessUp, exec, hyprctl hyprsunset gamma +10
bindle=, XF86MonBrightnessDown, exec, hyprctl hyprsunset gamma -10

bindm = Super, mouse:273, resizewindow # Resize

bind = SUPER, Right, workspace, +1
bind = SUPER, Left, workspace, -1
bind = SUPER, Down, exec, sh ~/.config/hypr/script/workspace_jump.sh 1
bind = SUPER, Up, exec, sh ~/.config/hypr/script/workspace_jump.sh 0

bind = SUPER+SHIFT, s, exec, grim -g "$(slurp)" - | swappy -f -
bind = SHIFT, Print, exec, grim - | wl-copy && wl-paste > ~/Pictures/screenshots/Screenshot-$(date +%F_%T).png && dunstify "Screenshot of the whole screen taken" -t 1000
bind = Super, I, exec, XDG_CURRENT_DESKTOP=gnome gnome-control-center
