[config]

[templates.rofi]
input_path = "~/.local/share/matugen/template/template.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.qt5ct]
input_path = '~/.local/share/matugen/template/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.starship]
input_path = '~/.local/share/matugen/template/settings.toml'
output_path = '~/.config/starship.toml'

[templates.kitty]
input_path = '~/.local/share/matugen/template/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.quickshell]
input_path = '~/.local/share/matugen/template/template.qml'
output_path = '~/.local/share/qs-bar/Theme/Colors.qml'

[templates.gtk3]
input_path = '~/.local/share/matugen/template/gtk_theme.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.local/share/matugen/template/gtk_theme.css'
output_path = '~/.config/gtk-4.0/colors.css'