exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"

exec-once = swww-daemon
exec-once = fcitx5
exec-once = ags run
exec-once = fcitx5-remote -r
exec-once = fcitx5 -d --replace &
exec-once = hyprsunset
exec-once = quickshell -p ~/.local/share/qs-bar/
