keys:
  - &desktop_user age1s4ysxqdgqz5s385zexttwl0scpgcvvnmsrl8czx6gdt4che7rsyq8yvdau
  - &msiLaptop age1qnjqtv5xp2xlqyxxakxnvcdnsfe9fzffslc8t2epxvw3mpaqyfyq2gmcjt
  # Run once desktop's host key is available, then uncomment and fill in:
  #   ssh desktop cat /etc/ssh/ssh_host_ed25519_key.pub | nix run github:Mic92/ssh-to-age
  - &desktop age15s5ua6y634ahcxzwkq3c6chjlpr875yc7lhqhqwqjepz7zwnyf6q3v5ndu
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *desktop_user
          - *msiLaptop
          - *desktop
