keys:
  - &msiLaptop age1696408cevgmckthrk0x773nl9slphwf3cz98agd3uqjsqdlg4duqt5jwpm
  - &desktop age1s4ysxqdgqz5s385zexttwl0scpgcvvnmsrl8czx6gdt4che7rsyq8yvdau
  - &msiLaptop_root age1qnjqtv5xp2xlqyxxakxnvcdnsfe9fzffslc8t2epxvw3mpaqyfyq2gmcjt
  - &desktop_root age15s5ua6y634ahcxzwkq3c6chjlpr875yc7lhqhqwqjepz7zwnyf6q3v5ndu
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *msiLaptop
          - *desktop
          - *msiLaptop_root
          - *desktop_root
